### PR TITLE
Improve breadcrumbs semantic and add HTML5 Microdata

### PR DESCRIPTION
**Pull request by GianlucaGuarini**
Fixes https://github.com/argyleink/gui-challenges/issues/44

It passes the [Google Rich Results Test](https://search.google.com/test/rich-results?id=mBTfJGQLtMW0kXj0mgARcQ) keeping the old functionalities. This Patch improves automatically its accessibility as well using the proper markup for the breadcrumb items.

Screenshot 2021-07-17 at 20 28 21

### CODE REVIEW

**Comment by argyleink** [comment]
nice, ty for this! would you mind adding an additional breadcrumb example instead of changing each of the existing?

**Comment by GianlucaGuarini** [comment]
@argyleink thank you for reviewing it. Sorry but I don't understand what you are proposing: should I create a new folder using this markup and calling it `semantic-breadcrumbs` or should I just add 1 HTML Example with semantic code?

Honestly I think that providing different markup solutions might be misleading for beginners and it feels not right to me. 
Please let me know if I can do anything to help you on this PR.

**Comment by argyleink** [comment]
Sorry, I'll try to be more clear! I think it'd be misleading also to come from an article or video that has different HTML than was found in the repo. If we're additive about this microdata example, and clearly label what it is and what it offers, then it feels like the best of both worlds. the original breadcrumbs are available, as well as a community contributed one! I think a new html and css file with the modified contents should do the trick well?

**Comment by GianlucaGuarini** [comment]
@argyleink I have updated my patch according to your suggestion. Please let me know if that works for you.

**Review by argyleink — APPROVED** [review]

**Comment by argyleink** [comment]
thanks for helping others by sharing your style!

**Pull request merged**
