### PR TITLE
Fixing accNames

### PR DESCRIPTION
**Pull request by aardrian**
The two "remove user" buttons should disambiguate which user, so I added a number (since there is no disambiguation anywhere else). I also swapped the `title` to `aria-label` since if the + is clear enough for the add button's audience, the × is would be clear enough for the remove buttons.

The real issue (as in, WCAG violation) is the lack of an accessible name on the add button. So I added an `aria-label`.

I was doing SR testing and got this far before I stopped. I am hoping you can run the entire demo through SR testing with the resources at Google.

### CODE REVIEW

**Review by argyleink — APPROVED** [review]

**Comment by argyleink** [comment]
There's no resources, just my time unfortunately.
Which SRs you testing with?

**Comment by aardrian** [comment]
> There's no resources, just my time unfortunately.

Ah. Since this is on the [Google Chrome Dev site](https://web.dev/building-a-dialog-component/), I assumed it was funded by Google.

> Which SRs you testing with?

Last night I only needed to check with JAWS because the issue was evident in the code and dev tools. But I usually test with JAWS, NVDA, VoiceOver (macOS and iOS), TalkBack, Narrator, and (if my VM is behaving) Orca.

Video with open captions and audio description demonstrating JAWS 20202 / Chrome 102 and a quick fix:
https://user-images.githubusercontent.com/1376607/174060299-0a04b059-cafe-44e9-acee-f0dbdf1ff70c.mp4

**Comment by argyleink** [comment]
squash and merge this when you're ready, i appreciate the additions 👍🏻

**Comment by aardrian** [comment]
I believe I need write access?

Also, am using the web UI — no command line, no installed version. So if there is no _Commit_ button I am mostly just blinking at the screen.

**Comment by argyleink** [comment]
oh! i thought my approval gave you the button, here, i'll smash it then!

**Pull request merged**
